# Generated by Django 2.2.4 on 2019-11-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact_no',
            new_name='contact',
        ),
    ]
